### ISSUE TITLE
Biome?

### ISSUE THREAD

**Issue by fkromer** [astro-community/AstroRome#123]
Would be great to have an integration for Romes successor https://github.com/biomejs/biome.

**Comment by NikolaRHristov** [comment]
Yes, it is planned, but I'm very busy, working on v1. It's almost ready just have to replace a few things. Expect an initial release soon.

**Comment by NikolaRHristov** [comment]
Sorry, I thought you posted this in the AstroBiome repository https://github.com/NikolaRHristov/astrobiome 😁 There's already a repository, just haven't tested it yet.

**Comment by NikolaRHristov** [comment]
AstroBiome released https://github.com/NikolaRHristov/AstroBiome
